name: Test Cases

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Testing_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - run: yarn install
      - run: yarn test
